import type { DatabaseType } from "@fixspace/domain";

export interface SeedRelation {
  type: DatabaseType;
  name: string;
}

export interface SeedRecord {
  name: string;
  icon?: string;
  values?: Record<string, unknown>;
  relations?: Record<string, SeedRelation | SeedRelation[]>;
}

const TRADING_SYSTEMS = [
  "Smart Money Concepts Core",
  "ICT London Kill Zone",
  "FVG + OB Confluence System",
  "Swing Structure Following",
  "XAUUSD Intraday Scalping",
];

function ts(i: number): SeedRelation {
  return { type: "trading-system", name: TRADING_SYSTEMS[i % TRADING_SYSTEMS.length]! };
}

export const seedsByDatabaseType: Partial<Record<DatabaseType, SeedRecord[]>> = {
  "trading-journal": [
    {
      name: "EURUSD Long — FVG Retracement",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-03",
        Pair: "EURUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.5,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "FVG",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "GBPUSD Short — Order Block Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-06",
        Pair: "GBPUSD",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 3.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "Order Block",
        "Entry Timeframe": "5m",
        "Point A": "SNR",
        "Point B": "Fractal",
        "Stop Loss position": "Above OB",
        Delivery: "Strong Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "USDJPY Short — BOS Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-08",
        Pair: "USDJPY",
        Session: "Asia",
        Direction: "Short",
        "Narrative TF": "1H",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "BOS",
        "Entry Timeframe": "15m",
        "Point A": "Fractal",
        "Point B": "FVG",
        "Stop Loss position": "Above Structure",
        Delivery: "Order Flow",
        "Session Confirm": "Asia",
        "Session Point": "Open",
      },
    },
    {
      name: "EURUSD Long — MSS Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-10",
        Pair: "EURUSD",
        Session: "Pre-London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 1.8,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "MSS",
        "Entry Timeframe": "5m",
        "Point A": "SNR",
        "Point B": "Premium DR",
        "Stop Loss position": "Below Structure",
        Delivery: "Order Flow",
        "Session Confirm": "Pre-London",
        "Session Point": "Low",
      },
    },
    {
      name: "XAUUSD Long — Breaker Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-13",
        Pair: "XAUUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 4.2,
        "Position Type": "Introweek",
        "Trade Position Type": "Continuation",
        "Entry Model": "Breaker Block",
        "Entry Timeframe": "1H",
        "Point A": "FVG",
        "Point B": "Discount DR",
        "Stop Loss position": "Below OB",
        Delivery: "Strong Order Flow",
        "Session Confirm": "London",
        "Session Point": "Open",
      },
    },
    {
      name: "GBPJPY Short — CISD Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-15",
        Pair: "GBPJPY",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Weekly",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Swing",
        "Trade Position Type": "Reversal",
        "Entry Model": "CISD",
        "Entry Timeframe": "4H",
        "Point A": "Fractal",
        "Point B": "SNR",
        "Stop Loss position": "Above Structure",
        Delivery: "Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "EURJPY Long — FVG Retracement",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-17",
        Pair: "EURJPY",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Break-even",
        "Gained RR": 0.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "FVG",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Sweep",
      },
    },
    {
      name: "EURUSD Short — Mitigation Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-20",
        Pair: "EURUSD",
        Session: "Pre-New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 2.1,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "Mitigation Block",
        "Entry Timeframe": "5m",
        "Point A": "Premium DR",
        "Point B": "FVG",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-New York",
        "Session Point": "Reversal",
      },
    },
    {
      name: "GBPUSD Long — Order Block Bounce",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-22",
        Pair: "GBPUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 3.5,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "Order Block",
        "Entry Timeframe": "15m",
        "Point A": "SNR",
        "Point B": "Fractal",
        "Stop Loss position": "Below OB",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "USDJPY Long — FVG Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-24",
        Pair: "USDJPY",
        Session: "Asia",
        Direction: "Long",
        "Narrative TF": "1H",
        Result: "Win",
        "Gained RR": 1.5,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "FVG",
        "Entry Timeframe": "5m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "Asia",
        "Session Point": "Open",
      },
    },
    {
      name: "XAUUSD Short — BOS Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-27",
        Pair: "XAUUSD",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "BOS",
        "Entry Timeframe": "1H",
        "Point A": "Fractal",
        "Point B": "FVG",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "EURUSD Long — CISD Setup",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-29",
        Pair: "EURUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.8,
        "Position Type": "Introweek",
        "Trade Position Type": "Continuation",
        "Entry Model": "CISD",
        "Entry Timeframe": "15m",
        "Point A": "SNR",
        "Point B": "Discount DR",
        "Stop Loss position": "Below Structure",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Sweep",
      },
    },
    {
      name: "GBPJPY Long — MSS Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-01-31",
        Pair: "GBPJPY",
        Session: "Pre-London",
        Direction: "Long",
        "Narrative TF": "Weekly",
        Result: "Win",
        "Gained RR": 5.0,
        "Position Type": "Swing",
        "Trade Position Type": "Reversal",
        "Entry Model": "MSS",
        "Entry Timeframe": "4H",
        "Point A": "FVG",
        "Point B": "Premium DR",
        "Stop Loss position": "Below FVG",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-London",
        "Session Point": "Low",
      },
    },
    {
      name: "EURJPY Short — Order Block Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-03",
        Pair: "EURJPY",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "Order Block",
        "Entry Timeframe": "5m",
        "Point A": "SNR",
        "Point B": "Fractal",
        "Stop Loss position": "Above OB",
        Delivery: "Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "EURUSD Short — Breaker Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-05",
        Pair: "EURUSD",
        Session: "London",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 2.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "Breaker Block",
        "Entry Timeframe": "15m",
        "Point A": "Premium DR",
        "Point B": "FVG",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "London",
        "Session Point": "Open",
      },
    },
    {
      name: "XAUUSD Long — FVG Retracement",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-07",
        Pair: "XAUUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 3.2,
        "Position Type": "Introweek",
        "Trade Position Type": "Retracement",
        "Entry Model": "FVG",
        "Entry Timeframe": "1H",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "GBPUSD Short — MSS Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-10",
        Pair: "GBPUSD",
        Session: "Pre-New York",
        Direction: "Short",
        "Narrative TF": "1H",
        Result: "Break-even",
        "Gained RR": 0.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "MSS",
        "Entry Timeframe": "5m",
        "Point A": "Fractal",
        "Point B": "SNR",
        "Stop Loss position": "Above Structure",
        Delivery: "Order Flow",
        "Session Confirm": "Pre-New York",
        "Session Point": "Sweep",
      },
    },
    {
      name: "USDJPY Short — FVG Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-12",
        Pair: "USDJPY",
        Session: "Asia",
        Direction: "Short",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 1.7,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "FVG",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "Discount DR",
        "Stop Loss position": "Below FVG",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Asia",
        "Session Point": "Open",
      },
    },
    {
      name: "EURUSD Long — Order Block Setup",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-14",
        Pair: "EURUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 2.3,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "Order Block",
        "Entry Timeframe": "15m",
        "Point A": "SNR",
        "Point B": "FVG",
        "Stop Loss position": "Below OB",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "XAUUSD Short — CISD Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-17",
        Pair: "XAUUSD",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Weekly",
        Result: "Win",
        "Gained RR": 4.8,
        "Position Type": "Swing",
        "Trade Position Type": "Reversal",
        "Entry Model": "CISD",
        "Entry Timeframe": "4H",
        "Point A": "Premium DR",
        "Point B": "SNR",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "EURJPY Long — BOS Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-19",
        Pair: "EURJPY",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.6,
        "Position Type": "Introweek",
        "Trade Position Type": "Continuation",
        "Entry Model": "BOS",
        "Entry Timeframe": "1H",
        "Point A": "FVG",
        "Point B": "Fractal",
        "Stop Loss position": "Below Structure",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Open",
      },
    },
    {
      name: "GBPUSD Long — Breaker Block Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-21",
        Pair: "GBPUSD",
        Session: "Pre-London",
        Direction: "Long",
        "Narrative TF": "Daily",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "Breaker Block",
        "Entry Timeframe": "5m",
        "Point A": "SNR",
        "Point B": "FVG",
        "Stop Loss position": "Below FVG",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-London",
        "Session Point": "Sweep",
      },
    },
    {
      name: "EURUSD Short — Mitigation Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-24",
        Pair: "EURUSD",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "1H",
        Result: "Win",
        "Gained RR": 1.9,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "Mitigation Block",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "Discount DR",
        "Stop Loss position": "Above Structure",
        Delivery: "Order Flow",
        "Session Confirm": "New York",
        "Session Point": "Reversal",
      },
    },
    {
      name: "USDJPY Long — Order Block Bounce",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-26",
        Pair: "USDJPY",
        Session: "Asia",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.2,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "Order Block",
        "Entry Timeframe": "15m",
        "Point A": "SNR",
        "Point B": "FVG",
        "Stop Loss position": "Below OB",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Asia",
        "Session Point": "Low",
      },
    },
    {
      name: "GBPJPY Short — FVG Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-02-28",
        Pair: "GBPJPY",
        Session: "London",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 3.1,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "FVG",
        "Entry Timeframe": "5m",
        "Point A": "Fractal",
        "Point B": "SNR",
        "Stop Loss position": "Above FVG",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "High",
      },
    },
    {
      name: "XAUUSD Long — MSS Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-03",
        Pair: "XAUUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "Weekly",
        Result: "Win",
        "Gained RR": 6.0,
        "Position Type": "Swing",
        "Trade Position Type": "Reversal",
        "Entry Model": "MSS",
        "Entry Timeframe": "4H",
        "Point A": "Discount DR",
        "Point B": "FVG",
        "Stop Loss position": "Below Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "EURUSD Long — CISD Setup",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-05",
        Pair: "EURUSD",
        Session: "Pre-London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Break-even",
        "Gained RR": 0.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "CISD",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "Pre-London",
        "Session Point": "Open",
      },
    },
    {
      name: "GBPUSD Short — BOS Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-07",
        Pair: "GBPUSD",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 2.7,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "BOS",
        "Entry Timeframe": "1H",
        "Point A": "Premium DR",
        "Point B": "Fractal",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "EURJPY Short — Order Block Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-10",
        Pair: "EURJPY",
        Session: "London",
        Direction: "Short",
        "Narrative TF": "1H",
        Result: "Win",
        "Gained RR": 1.6,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "Order Block",
        "Entry Timeframe": "5m",
        "Point A": "SNR",
        "Point B": "FVG",
        "Stop Loss position": "Above OB",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Sweep",
      },
    },
    {
      name: "USDJPY Long — Breaker Block Bounce",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-12",
        Pair: "USDJPY",
        Session: "Asia",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "Breaker Block",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Asia",
        "Session Point": "Open",
      },
    },
    {
      name: "XAUUSD Long — Mitigation Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-14",
        Pair: "XAUUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 3.8,
        "Position Type": "Introweek",
        "Trade Position Type": "Continuation",
        "Entry Model": "Mitigation Block",
        "Entry Timeframe": "1H",
        "Point A": "Discount DR",
        "Point B": "FVG",
        "Stop Loss position": "Below Structure",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "EURUSD Short — FVG Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-17",
        Pair: "EURUSD",
        Session: "Pre-New York",
        Direction: "Short",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.4,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "FVG",
        "Entry Timeframe": "5m",
        "Point A": "Premium DR",
        "Point B": "SNR",
        "Stop Loss position": "Above FVG",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-New York",
        "Session Point": "High",
      },
    },
    {
      name: "GBPJPY Long — CISD Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-19",
        Pair: "GBPJPY",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "Weekly",
        Result: "Win",
        "Gained RR": 4.5,
        "Position Type": "Swing",
        "Trade Position Type": "Continuation",
        "Entry Model": "CISD",
        "Entry Timeframe": "4H",
        "Point A": "FVG",
        "Point B": "Discount DR",
        "Stop Loss position": "Below Structure",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Open",
      },
    },
    {
      name: "EURJPY Long — MSS Retracement",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-21",
        Pair: "EURJPY",
        Session: "Pre-London",
        Direction: "Long",
        "Narrative TF": "Daily",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "MSS",
        "Entry Timeframe": "15m",
        "Point A": "SNR",
        "Point B": "FVG",
        "Stop Loss position": "Below Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-London",
        "Session Point": "Sweep",
      },
    },
    {
      name: "GBPUSD Long — FVG Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-24",
        Pair: "GBPUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.9,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "FVG",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "USDJPY Short — CISD Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-26",
        Pair: "USDJPY",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 2.1,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "CISD",
        "Entry Timeframe": "1H",
        "Point A": "Premium DR",
        "Point B": "Fractal",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "XAUUSD Long — Order Block Bounce",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-28",
        Pair: "XAUUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 3.6,
        "Position Type": "Introweek",
        "Trade Position Type": "Retracement",
        "Entry Model": "Order Block",
        "Entry Timeframe": "1H",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below OB",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "EURUSD Long — BOS Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-03-31",
        Pair: "EURUSD",
        Session: "Pre-London",
        Direction: "Long",
        "Narrative TF": "1H",
        Result: "Win",
        "Gained RR": 1.4,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "BOS",
        "Entry Timeframe": "5m",
        "Point A": "FVG",
        "Point B": "Discount DR",
        "Stop Loss position": "Below Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-London",
        "Session Point": "Open",
      },
    },
    {
      name: "GBPUSD Short — Mitigation Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-02",
        Pair: "GBPUSD",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 2.2,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "Mitigation Block",
        "Entry Timeframe": "15m",
        "Point A": "SNR",
        "Point B": "FVG",
        "Stop Loss position": "Above Structure",
        Delivery: "Order Flow",
        "Session Confirm": "New York",
        "Session Point": "Reversal",
      },
    },
    {
      name: "EURJPY Short — Breaker Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-04",
        Pair: "EURJPY",
        Session: "London",
        Direction: "Short",
        "Narrative TF": "4H",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "Breaker Block",
        "Entry Timeframe": "5m",
        "Point A": "Fractal",
        "Point B": "SNR",
        "Stop Loss position": "Above FVG",
        Delivery: "Strong Order Flow",
        "Session Confirm": "London",
        "Session Point": "High",
      },
    },
    {
      name: "XAUUSD Short — BOS Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-07",
        Pair: "XAUUSD",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Weekly",
        Result: "Win",
        "Gained RR": 5.2,
        "Position Type": "Swing",
        "Trade Position Type": "Reversal",
        "Entry Model": "BOS",
        "Entry Timeframe": "4H",
        "Point A": "Premium DR",
        "Point B": "Fractal",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "EURUSD Long — FVG Bounce",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-09",
        Pair: "EURUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "FVG",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "GBPJPY Short — Order Block Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-11",
        Pair: "GBPJPY",
        Session: "Pre-New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 3.3,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "Order Block",
        "Entry Timeframe": "1H",
        "Point A": "SNR",
        "Point B": "Fractal",
        "Stop Loss position": "Above OB",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-New York",
        "Session Point": "High",
      },
    },
    {
      name: "USDJPY Long — MSS Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-14",
        Pair: "USDJPY",
        Session: "Asia",
        Direction: "Long",
        "Narrative TF": "1H",
        Result: "Win",
        "Gained RR": 1.8,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "MSS",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below Structure",
        Delivery: "Order Flow",
        "Session Confirm": "Asia",
        "Session Point": "Open",
      },
    },
    {
      name: "EURUSD Short — CISD Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-16",
        Pair: "EURUSD",
        Session: "London",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Break-even",
        "Gained RR": 0.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "CISD",
        "Entry Timeframe": "5m",
        "Point A": "Premium DR",
        "Point B": "FVG",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "London",
        "Session Point": "Sweep",
      },
    },
    {
      name: "GBPUSD Long — Breaker Block Entry",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-18",
        Pair: "GBPUSD",
        Session: "Pre-London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.5,
        "Position Type": "Intraday",
        "Trade Position Type": "Retracement",
        "Entry Model": "Breaker Block",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "Pre-London",
        "Session Point": "Low",
      },
    },
    {
      name: "XAUUSD Long — CISD Retracement",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-21",
        Pair: "XAUUSD",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "Weekly",
        Result: "Win",
        "Gained RR": 4.1,
        "Position Type": "Swing",
        "Trade Position Type": "Retracement",
        "Entry Model": "CISD",
        "Entry Timeframe": "4H",
        "Point A": "Discount DR",
        "Point B": "FVG",
        "Stop Loss position": "Below Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "EURJPY Long — FVG Continuation",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-23",
        Pair: "EURJPY",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 2.3,
        "Position Type": "Intraday",
        "Trade Position Type": "Continuation",
        "Entry Model": "FVG",
        "Entry Timeframe": "15m",
        "Point A": "FVG",
        "Point B": "SNR",
        "Stop Loss position": "Below FVG",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Open",
      },
    },
    {
      name: "USDJPY Short — Mitigation Block",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-25",
        Pair: "USDJPY",
        Session: "New York",
        Direction: "Short",
        "Narrative TF": "Daily",
        Result: "Loss",
        "Gained RR": -1.0,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "Mitigation Block",
        "Entry Timeframe": "1H",
        "Point A": "SNR",
        "Point B": "Fractal",
        "Stop Loss position": "Above Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "New York",
        "Session Point": "High",
      },
    },
    {
      name: "GBPJPY Long — Order Block Bounce",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-28",
        Pair: "GBPJPY",
        Session: "London",
        Direction: "Long",
        "Narrative TF": "4H",
        Result: "Win",
        "Gained RR": 3.0,
        "Position Type": "Introweek",
        "Trade Position Type": "Retracement",
        "Entry Model": "Order Block",
        "Entry Timeframe": "15m",
        "Point A": "SNR",
        "Point B": "FVG",
        "Stop Loss position": "Below OB",
        Delivery: "Order Flow",
        "Session Confirm": "London",
        "Session Point": "Low",
      },
    },
    {
      name: "EURUSD Long — BOS Reversal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: {
        Date: "2025-04-30",
        Pair: "EURUSD",
        Session: "Pre-New York",
        Direction: "Long",
        "Narrative TF": "Daily",
        Result: "Win",
        "Gained RR": 2.6,
        "Position Type": "Intraday",
        "Trade Position Type": "Reversal",
        "Entry Model": "BOS",
        "Entry Timeframe": "5m",
        "Point A": "Discount DR",
        "Point B": "SNR",
        "Stop Loss position": "Below Structure",
        Delivery: "Strong Order Flow",
        "Session Confirm": "Pre-New York",
        "Session Point": "Reversal",
      },
    },
  ],

  "daily-routine": [
    {
      name: "EURUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-01-03", Pair: "EURUSD", Outcome: "Win" },
    },
    {
      name: "GBPUSD New York Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(1) },
      values: { Date: "2025-01-06", Pair: "GBPUSD", Outcome: "Win" },
    },
    {
      name: "XAUUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(2) },
      values: { Date: "2025-01-08", Pair: "XAUUSD", Outcome: "Loss" },
    },
    {
      name: "USDJPY Asia Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(3) },
      values: { Date: "2025-01-10", Pair: "USDJPY", Outcome: "Win" },
    },
    {
      name: "EURUSD Pre-London Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(4) },
      values: { Date: "2025-01-13", Pair: "EURUSD", Outcome: "Win" },
    },
    {
      name: "GBPJPY London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-01-15", Pair: "GBPJPY", Outcome: "Break-even" },
    },
    {
      name: "EURJPY New York Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(1) },
      values: { Date: "2025-01-17", Pair: "EURJPY", Outcome: "Win" },
    },
    {
      name: "XAUUSD Pre-New York Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(4) },
      values: { Date: "2025-01-20", Pair: "XAUUSD", Outcome: "Win" },
    },
    {
      name: "EURUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-01-22", Pair: "EURUSD", Outcome: "Loss" },
    },
    {
      name: "GBPUSD Asia Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(1) },
      values: { Date: "2025-01-24", Pair: "GBPUSD", Outcome: "Win" },
    },
    {
      name: "USDJPY London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(2) },
      values: { Date: "2025-01-27", Pair: "USDJPY", Outcome: "Win" },
    },
    {
      name: "EURUSD New York Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-01-29", Pair: "EURUSD", Outcome: "Win" },
    },
    {
      name: "GBPJPY Pre-London Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(1) },
      values: { Date: "2025-01-31", Pair: "GBPJPY", Outcome: "Win" },
    },
    {
      name: "XAUUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(4) },
      values: { Date: "2025-02-03", Pair: "XAUUSD", Outcome: "Loss" },
    },
    {
      name: "EURJPY London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-02-05", Pair: "EURJPY", Outcome: "Win" },
    },
    {
      name: "EURUSD Asia Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(2) },
      values: { Date: "2025-02-07", Pair: "EURUSD", Outcome: "Break-even" },
    },
    {
      name: "GBPUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-02-10", Pair: "GBPUSD", Outcome: "Win" },
    },
    {
      name: "XAUUSD New York Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(4) },
      values: { Date: "2025-02-12", Pair: "XAUUSD", Outcome: "Win" },
    },
    {
      name: "USDJPY Pre-London Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(3) },
      values: { Date: "2025-02-14", Pair: "USDJPY", Outcome: "Win" },
    },
    {
      name: "EURUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-02-17", Pair: "EURUSD", Outcome: "Win" },
    },
    {
      name: "GBPJPY New York Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(1) },
      values: { Date: "2025-02-19", Pair: "GBPJPY", Outcome: "Loss" },
    },
    {
      name: "EURJPY Asia Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(2) },
      values: { Date: "2025-02-21", Pair: "EURJPY", Outcome: "Win" },
    },
    {
      name: "XAUUSD Pre-London Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(4) },
      values: { Date: "2025-02-24", Pair: "XAUUSD", Outcome: "Win" },
    },
    {
      name: "GBPUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-02-26", Pair: "GBPUSD", Outcome: "Win" },
    },
    {
      name: "EURUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(1) },
      values: { Date: "2025-02-28", Pair: "EURUSD", Outcome: "Break-even" },
    },
    {
      name: "USDJPY New York Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(3) },
      values: { Date: "2025-03-03", Pair: "USDJPY", Outcome: "Win" },
    },
    {
      name: "XAUUSD London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(4) },
      values: { Date: "2025-03-05", Pair: "XAUUSD", Outcome: "Win" },
    },
    {
      name: "GBPJPY Pre-New York Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(0) },
      values: { Date: "2025-03-07", Pair: "GBPJPY", Outcome: "Win" },
    },
    {
      name: "EURJPY London Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(2) },
      values: { Date: "2025-03-10", Pair: "EURJPY", Outcome: "Loss" },
    },
    {
      name: "EURUSD Asia Session Analysis",
      relations: { Account: { type: "accounts", name: "Personal Live Account" }, "Trading System": ts(1) },
      values: { Date: "2025-03-12", Pair: "EURUSD", Outcome: "Win" },
    },
  ],

  notes: [
    {
      name: "FVG Entry Rules",
      values: { Date: "2025-01-05", Type: "Rule", Topic: "Entry", "Used in Trades": 12, "Used in Analysis": 18 },
    },
    {
      name: "Order Block Identification",
      values: {
        Date: "2025-01-08",
        Type: "Observation",
        Topic: "Analysis",
        "Used in Trades": 8,
        "Used in Analysis": 15,
      },
    },
    {
      name: "Risk Management: 1% Rule",
      values: {
        Date: "2025-01-10",
        Type: "Rule",
        Topic: "Risk Management",
        "Used in Trades": 50,
        "Used in Analysis": 5,
      },
    },
    {
      name: "Psychology: Dealing with Losses",
      values: {
        Date: "2025-01-13",
        Type: "Psychology",
        Topic: "Psychology",
        "Used in Trades": 3,
        "Used in Analysis": 7,
      },
    },
    {
      name: "London Session Open Dynamics",
      values: { Date: "2025-01-15", Type: "Lesson", Topic: "Analysis", "Used in Trades": 20, "Used in Analysis": 30 },
    },
    {
      name: "Confluence: Multiple Timeframe Analysis",
      values: { Date: "2025-01-17", Type: "Strategy", Topic: "Analysis", "Used in Trades": 15, "Used in Analysis": 25 },
    },
    {
      name: "Stop Loss Placement Behind Structure",
      values: {
        Date: "2025-01-20",
        Type: "Rule",
        Topic: "Risk Management",
        "Used in Trades": 45,
        "Used in Analysis": 10,
      },
    },
    {
      name: "MSS: Market Structure Shift Confirmation",
      values: { Date: "2025-01-22", Type: "Observation", Topic: "Entry", "Used in Trades": 10, "Used in Analysis": 22 },
    },
    {
      name: "Trading During High Impact News",
      values: {
        Date: "2025-01-24",
        Type: "Rule",
        Topic: "Risk Management",
        "Used in Trades": 30,
        "Used in Analysis": 5,
      },
    },
    {
      name: "XAUUSD Volatility Characteristics",
      values: {
        Date: "2025-01-27",
        Type: "Observation",
        Topic: "Analysis",
        "Used in Trades": 6,
        "Used in Analysis": 14,
      },
    },
    {
      name: "New York Session Trap Patterns",
      values: { Date: "2025-01-29", Type: "Lesson", Topic: "Analysis", "Used in Trades": 9, "Used in Analysis": 16 },
    },
    {
      name: "Patience: Waiting for Confirmation",
      values: {
        Date: "2025-01-31",
        Type: "Psychology",
        Topic: "Psychology",
        "Used in Trades": 5,
        "Used in Analysis": 8,
      },
    },
    {
      name: "BOS vs MSS Distinction",
      values: { Date: "2025-02-03", Type: "Lesson", Topic: "Analysis", "Used in Trades": 14, "Used in Analysis": 28 },
    },
    {
      name: "Position Sizing Based on Account %",
      values: {
        Date: "2025-02-05",
        Type: "Rule",
        Topic: "Risk Management",
        "Used in Trades": 50,
        "Used in Analysis": 3,
      },
    },
    {
      name: "Breaker Block Formation Rules",
      values: { Date: "2025-02-07", Type: "Strategy", Topic: "Entry", "Used in Trades": 7, "Used in Analysis": 12 },
    },
    {
      name: "Pre-London Accumulation Phase",
      values: {
        Date: "2025-02-10",
        Type: "Observation",
        Topic: "Analysis",
        "Used in Trades": 11,
        "Used in Analysis": 20,
      },
    },
    {
      name: "Exit Strategy: Partial Take Profits",
      values: { Date: "2025-02-12", Type: "Strategy", Topic: "Exit", "Used in Trades": 18, "Used in Analysis": 6 },
    },
    {
      name: "CISD: Change in State of Delivery",
      values: { Date: "2025-02-14", Type: "Lesson", Topic: "Entry", "Used in Trades": 8, "Used in Analysis": 19 },
    },
    {
      name: "Correlation: EURUSD and DXY",
      values: {
        Date: "2025-02-17",
        Type: "Observation",
        Topic: "Analysis",
        "Used in Trades": 4,
        "Used in Analysis": 11,
      },
    },
    {
      name: "Weekly Bias Setting Process",
      values: { Date: "2025-02-19", Type: "Strategy", Topic: "Analysis", "Used in Trades": 22, "Used in Analysis": 35 },
    },
  ],

  mistakes: [
    {
      name: "Entered without session confirmation",
      values: { Date: "2025-01-06", Type: "Discipline", Topic: "Entry", "Used in Trades": 5, "Used in Analysis": 3 },
    },
    {
      name: "Moved stop loss to break-even too early",
      values: {
        Date: "2025-01-10",
        Type: "Execution",
        Topic: "Risk Management",
        "Used in Trades": 8,
        "Used in Analysis": 4,
      },
    },
    {
      name: "Traded during high-impact news",
      values: {
        Date: "2025-01-15",
        Type: "Discipline",
        Topic: "Risk Management",
        "Used in Trades": 3,
        "Used in Analysis": 2,
      },
    },
    {
      name: "Overtraded after a loss",
      values: {
        Date: "2025-01-20",
        Type: "Psychology",
        Topic: "Psychology",
        "Used in Trades": 4,
        "Used in Analysis": 5,
      },
    },
    {
      name: "Ignored daily bias for entry direction",
      values: { Date: "2025-01-24", Type: "Analysis", Topic: "Analysis", "Used in Trades": 6, "Used in Analysis": 7 },
    },
    {
      name: "Used wrong timeframe for entry",
      values: { Date: "2025-01-29", Type: "Execution", Topic: "Entry", "Used in Trades": 7, "Used in Analysis": 3 },
    },
    {
      name: "Closed trade too early at first TP",
      values: { Date: "2025-02-03", Type: "Execution", Topic: "Exit", "Used in Trades": 9, "Used in Analysis": 2 },
    },
    {
      name: "Risked more than 1% on single trade",
      values: {
        Date: "2025-02-07",
        Type: "Risk Management",
        Topic: "Risk Management",
        "Used in Trades": 2,
        "Used in Analysis": 6,
      },
    },
    {
      name: "Took trade without clear narrative",
      values: { Date: "2025-02-12", Type: "Analysis", Topic: "Analysis", "Used in Trades": 5, "Used in Analysis": 8 },
    },
    {
      name: "Entered on first touch of OB without confirmation",
      values: { Date: "2025-02-17", Type: "Execution", Topic: "Entry", "Used in Trades": 4, "Used in Analysis": 5 },
    },
    {
      name: "Revenge traded after drawdown",
      values: {
        Date: "2025-02-21",
        Type: "Psychology",
        Topic: "Psychology",
        "Used in Trades": 3,
        "Used in Analysis": 4,
      },
    },
    {
      name: "Misidentified FVG direction",
      values: { Date: "2025-02-26", Type: "Analysis", Topic: "Analysis", "Used in Trades": 6, "Used in Analysis": 9 },
    },
    {
      name: "Forgot to adjust SL after partial close",
      values: {
        Date: "2025-03-03",
        Type: "Execution",
        Topic: "Risk Management",
        "Used in Trades": 4,
        "Used in Analysis": 3,
      },
    },
    {
      name: "Traded against weekly bias",
      values: { Date: "2025-03-07", Type: "Discipline", Topic: "Analysis", "Used in Trades": 3, "Used in Analysis": 7 },
    },
    {
      name: "Sized up position on a losing streak",
      values: {
        Date: "2025-03-12",
        Type: "Risk Management",
        Topic: "Risk Management",
        "Used in Trades": 2,
        "Used in Analysis": 5,
      },
    },
  ],

  accounts: [
    {
      name: "Personal Live Account",
      values: {
        Started: "2025-01-01",
        "Account Type": "Personal",
        Status: { label: "In progress", color: "#2563EB" },
        "Starting Equity": 5000,
        "Current Equity": 6250,
      },
      relations: {
        Operations: [
          { type: "operations", name: "Initial deposit — Personal" },
          { type: "operations", name: "Profit withdrawal — Personal" },
          { type: "operations", name: "Top-up — Personal" },
          { type: "operations", name: "Personal account profit pull" },
          { type: "operations", name: "Personal deposit top-up" },
          { type: "operations", name: "Monthly personal withdrawal" },
          { type: "operations", name: "Personal account deposit" },
          { type: "operations", name: "Personal withdrawal — April" },
          { type: "operations", name: "Year-end personal withdrawal" },
        ],
      },
    },
    {
      name: "FTMO Challenge",
      values: {
        Started: "2025-01-15",
        "Account Type": "Challenge",
        Status: { label: "In progress", color: "#2563EB" },
        "Starting Equity": 100000,
        "Current Equity": 103500,
      },
      relations: {
        Operations: [
          { type: "operations", name: "FTMO Challenge fee" },
          { type: "operations", name: "Challenge second attempt fee" },
          { type: "operations", name: "Challenge phase 2 deposit" },
        ],
      },
    },
    {
      name: "Demo Practice Account",
      values: {
        Started: "2024-11-01",
        "Account Type": "Demo",
        Status: { label: "In progress", color: "#2563EB" },
        "Starting Equity": 10000,
        "Current Equity": 11800,
      },
      relations: {
        Operations: [
          { type: "operations", name: "Demo account setup" },
          { type: "operations", name: "Demo reset deposit" },
          { type: "operations", name: "Demo account deposit" },
        ],
      },
    },
    {
      name: "Funded Prop Account",
      values: {
        Started: "2025-03-01",
        "Account Type": "Funded",
        Status: { label: "Done", color: "#16A34A" },
        "Starting Equity": 50000,
        "Current Equity": 51200,
      },
      relations: {
        Operations: [
          { type: "operations", name: "Funded account initial equity" },
          { type: "operations", name: "Funded payout request" },
          { type: "operations", name: "Funded account top-up" },
          { type: "operations", name: "Funded payout — April" },
          { type: "operations", name: "Funded bonus payout" },
        ],
      },
    },
  ],

  operations: [
    {
      name: "Initial deposit — Personal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Deposit", Date: "2025-01-01", Amount: 5000 },
    },
    {
      name: "Profit withdrawal — Personal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Withdrawal", Date: "2025-01-31", Amount: 500 },
    },
    {
      name: "Top-up — Personal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Deposit", Date: "2025-03-01", Amount: 1000 },
    },
    {
      name: "FTMO Challenge fee",
      relations: { Account: { type: "accounts", name: "FTMO Challenge" } },
      values: { Type: "Deposit", Date: "2025-01-15", Amount: 540 },
    },
    {
      name: "Demo account setup",
      relations: { Account: { type: "accounts", name: "Demo Practice Account" } },
      values: { Type: "Deposit", Date: "2024-11-01", Amount: 10000 },
    },
    {
      name: "Demo reset deposit",
      relations: { Account: { type: "accounts", name: "Demo Practice Account" } },
      values: { Type: "Deposit", Date: "2024-12-01", Amount: 10000 },
    },
    {
      name: "Funded account initial equity",
      relations: { Account: { type: "accounts", name: "Funded Prop Account" } },
      values: { Type: "Deposit", Date: "2025-03-01", Amount: 50000 },
    },
    {
      name: "Funded payout request",
      relations: { Account: { type: "accounts", name: "Funded Prop Account" } },
      values: { Type: "Withdrawal", Date: "2025-03-31", Amount: 1200 },
    },
    {
      name: "Personal account profit pull",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Withdrawal", Date: "2025-02-28", Amount: 750 },
    },
    {
      name: "Challenge second attempt fee",
      relations: { Account: { type: "accounts", name: "FTMO Challenge" } },
      values: { Type: "Deposit", Date: "2025-02-10", Amount: 540 },
    },
    {
      name: "Personal deposit top-up",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Deposit", Date: "2025-02-15", Amount: 500 },
    },
    {
      name: "Funded account top-up",
      relations: { Account: { type: "accounts", name: "Funded Prop Account" } },
      values: { Type: "Deposit", Date: "2025-03-15", Amount: 5000 },
    },
    {
      name: "Monthly personal withdrawal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Withdrawal", Date: "2025-03-31", Amount: 600 },
    },
    {
      name: "Demo account deposit",
      relations: { Account: { type: "accounts", name: "Demo Practice Account" } },
      values: { Type: "Deposit", Date: "2025-02-01", Amount: 10000 },
    },
    {
      name: "Funded payout — April",
      relations: { Account: { type: "accounts", name: "Funded Prop Account" } },
      values: { Type: "Withdrawal", Date: "2025-04-30", Amount: 1500 },
    },
    {
      name: "Personal account deposit",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Deposit", Date: "2025-04-01", Amount: 1000 },
    },
    {
      name: "Personal withdrawal — April",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Withdrawal", Date: "2025-04-30", Amount: 800 },
    },
    {
      name: "Challenge phase 2 deposit",
      relations: { Account: { type: "accounts", name: "FTMO Challenge" } },
      values: { Type: "Deposit", Date: "2025-03-05", Amount: 540 },
    },
    {
      name: "Funded bonus payout",
      relations: { Account: { type: "accounts", name: "Funded Prop Account" } },
      values: { Type: "Withdrawal", Date: "2025-04-15", Amount: 2000 },
    },
    {
      name: "Year-end personal withdrawal",
      relations: { Account: { type: "accounts", name: "Personal Live Account" } },
      values: { Type: "Withdrawal", Date: "2025-04-30", Amount: 1000 },
    },
  ],

  "trading-system": [
    { name: "Smart Money Concepts Core", values: { Date: "2025-01-01" } },
    { name: "ICT London Kill Zone", values: { Date: "2025-01-15" } },
    { name: "FVG + OB Confluence System", values: { Date: "2025-02-01" } },
    { name: "Swing Structure Following", values: { Date: "2025-02-15" } },
    { name: "XAUUSD Intraday Scalping", values: { Date: "2025-03-01" } },
  ],
};
