import { PropertyType } from "@fixspace/domain";
import { DATE_CONFIG } from "../constants";
import type { InitPropertyDef } from "../types";

export const performanceReviewProperties: InitPropertyDef[] = [
  {
    name: "Name",
    type: PropertyType.TEXT,
    position: 0,
    hint: "Заголовок огляду.",
  },
  {
    name: "Date",
    type: PropertyType.DATE,
    position: 1,
    icon: "icon:Calendar",
    config: DATE_CONFIG,
    hint: "Дата проведення глибокого аналізу.",
  },
  {
    name: "Period",
    type: PropertyType.SELECT,
    position: 2,
    icon: "icon:CalendarRange",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Period",
          options: [
            { value: "Weekly", color: "#2563EB" },
            { value: "Monthly", color: "#7C3AED" },
            { value: "Quarterly", color: "#D97706" },
          ],
        },
      ],
    },
    hint: "Тип аналізованого відрізку часу.",
  },
  {
    name: "Period Start",
    type: PropertyType.DATE,
    position: 3,
    icon: "icon:CalendarArrowUp",
    config: DATE_CONFIG,
    hint: "Дата початку аналізованого відрізку.",
  },
  {
    name: "Period End",
    type: PropertyType.DATE,
    position: 4,
    icon: "icon:CalendarArrowDown",
    config: DATE_CONFIG,
    hint: "Дата кінця аналізованого відрізку.",
  },
  {
    name: "Grade",
    type: PropertyType.SELECT,
    position: 5,
    icon: "icon:Star",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Grade",
          options: [
            { value: "A", color: "#16A34A" },
            { value: "B", color: "#2563EB" },
            { value: "C", color: "#CA8A04" },
            { value: "D", color: "#D97706" },
            { value: "F", color: "#DC2626" },
          ],
        },
      ],
    },
    hint: "Суб'єктивна загальна оцінка роботи за период.",
  },
  {
    name: "Net P&L",
    type: PropertyType.FORMULA,
    position: 6,
    config: {
      type: "CUSTOM",
      expression: "SUM(MAP({{Trades}}, 'Net P&L'))",
      resultType: "NUMBER",
    },
    hint: "Чистий фінансовий результат за всіма угодами.",
  },
  {
    name: "Gross P&L",
    type: PropertyType.FORMULA,
    position: 7,
    config: {
      type: "CUSTOM",
      expression: "SUM(MAP({{Trades}}, 'Gross P&L'))",
      resultType: "NUMBER",
    },
    hint: "Валовий P&L до комісій та свопів.",
  },
  {
    name: "Trade Count",
    type: PropertyType.FORMULA,
    position: 8,
    config: {
      type: "CUSTOM",
      expression: "COUNT({{Trades}})",
      resultType: "NUMBER",
    },
    hint: "Кількість угод за період.",
  },
  {
    name: "Win Rate",
    type: PropertyType.FORMULA,
    position: 9,
    config: {
      type: "CUSTOM",
      expression: "IF(COUNT({{Trades}}) == 0, 0, SUM(MAP({{Trades}}, 'Is Win')) / COUNT({{Trades}}) * 100)",
      resultType: "NUMBER",
    },
    hint: "Відсоток виграшних угод.",
  },
  {
    name: "Total R",
    type: PropertyType.FORMULA,
    position: 10,
    config: {
      type: "CUSTOM",
      expression: "SUM(MAP({{Trades}}, 'Actual R'))",
      resultType: "NUMBER",
    },
    hint: "Сумарний R за всіма угодами.",
  },
  {
    name: "Avg R",
    type: PropertyType.FORMULA,
    position: 11,
    config: {
      type: "CUSTOM",
      expression: "IF(COUNT({{Trades}}) == 0, 0, AVG(MAP({{Trades}}, 'Actual R')))",
      resultType: "NUMBER",
    },
    hint: "Середній R на угоду.",
  },
  {
    name: "Max R",
    type: PropertyType.FORMULA,
    position: 12,
    config: {
      type: "CUSTOM",
      expression: "MAX(MAP({{Trades}}, 'Actual R'))",
      resultType: "NUMBER",
    },
    hint: "Найкращий R за угоду у цьому огляді.",
  },
  {
    name: "Min R",
    type: PropertyType.FORMULA,
    position: 13,
    config: {
      type: "CUSTOM",
      expression: "MIN(MAP({{Trades}}, 'Actual R'))",
      resultType: "NUMBER",
    },
    hint: "Найгірший R за угоду (максимальний збиток у R).",
  },
  {
    name: "Profit Factor",
    type: PropertyType.NUMBER,
    position: 14,
    config: { defaultValue: 0, format: "float", decimalPlaces: 2 },
    hint: "Profit Factor: валовий прибуток / валовий збиток.",
  },
  {
    name: "Max Drawdown %",
    type: PropertyType.NUMBER,
    position: 15,
    icon: "icon:TrendingDown",
    config: { defaultValue: 0, format: "float", decimalPlaces: 2 },
    hint: "Максимальне просідання капіталу за період у %.",
  },
  {
    name: "Discipline Score",
    type: PropertyType.RATING,
    position: 16,
    icon: "icon:Target",
    config: { maxStars: 5, allowHalf: true },
    hint: "Оцінка дотримання торгового плану та правил.",
  },
  {
    name: "Psychology Score",
    type: PropertyType.RATING,
    position: 17,
    icon: "icon:Brain",
    config: { maxStars: 5, allowHalf: true },
    hint: "Оцінка психологічного стану та управління емоціями.",
  },
  {
    name: "Process Score",
    type: PropertyType.RATING,
    position: 18,
    icon: "icon:ClipboardCheck",
    config: { maxStars: 5, allowHalf: true },
    hint: "Оцінка якості процесу: аналіз, ведення журналу, рутина.",
  },
  {
    name: "Trades",
    type: PropertyType.RELATION,
    position: 19,
    config: { sourceDatabaseType: "trading-journal", multiple: true },
    hint: "Усі угоди, включені у цей огляд.",
  },
  {
    name: "Mistakes",
    type: PropertyType.RELATION,
    position: 20,
    config: { sourceDatabaseType: "mistakes", multiple: true },
    hint: "Ключові помилки, допущені протягом цього відрізку.",
  },
  {
    name: "Daily Routines",
    type: PropertyType.RELATION,
    position: 21,
    config: { sourceDatabaseType: "daily-routine", multiple: true },
    hint: "Щоденні рутини, що охоплюють цей відрізок.",
  },
  {
    name: "Trading Systems",
    type: PropertyType.RELATION,
    position: 22,
    config: { sourceDatabaseType: "trading-system", multiple: true },
    hint: "Торгові системи, що використовувались у цьому відрізку.",
  },
  {
    name: "Notes",
    type: PropertyType.RELATION,
    position: 23,
    config: { sourceDatabaseType: "notes", multiple: true },
    hint: "Пов'язані нотатки та інсайти по цьому відрізку.",
  },
];
