import { PropertyType } from "@fixspace/domain";
import { colors, DATE_CONFIG, DIRECTION_OPTIONS, PAIR_CATEGORIES, SESSION_OPTIONS, TIMEFRAME_OPTIONS, FORMULA_TEXT } from "../constants";
import type { InitPropertyDef } from "../types";

export const tradingJournalProperties: InitPropertyDef[] = [
  {
    name: "Name",
    type: PropertyType.TEXT,
    position: 0,
    hint: "Короткий ідентифікатор угоди для швидкого пошуку в списку.",
    group: "Execution",
  },
  {
    name: "Status",
    type: PropertyType.SELECT,
    position: 1,
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Status",
          options: [
            { value: "Active", color: colors.blue },
            { value: "Closed", color: colors.gray },
          ],
        },
      ],
    },
    hint: "Відображає життєвий цикл угоди: від ідеї до повного закриття.",
    group: "Execution",
  },
  {
    name: "Pair",
    type: PropertyType.SELECT,
    position: 2,
    config: { isMultiSelect: false, categories: PAIR_CATEGORIES },
    hint: "Конкретний актив. Дозволяє виявити, на яких інструментах ваша стратегія працює найкраще.",
    group: "Execution",
  },
  {
    name: "Direction",
    type: PropertyType.SELECT,
    position: 3,
    config: { isMultiSelect: false, categories: [{ label: "Direction", options: DIRECTION_OPTIONS }] },
    hint: "Напрямок позиції. Важливо для аналізу перекосів.",
    group: "Execution",
  },
  {
    name: "Entry Price",
    type: PropertyType.NUMBER,
    position: 4,
    config: { defaultValue: 0, format: "float" },
    hint: "Точна ціна виконання ордера. Фундамент для розрахунку P&L та R-кратного.",
    group: "Execution",
  },
  {
    name: "Exit Price",
    type: PropertyType.NUMBER,
    position: 5,
    config: { defaultValue: 0, format: "float" },
    hint: "Середня ціна виходу. Дозволяє розрахувати фактичну ефективність угоди.",
    group: "Execution",
  },
  {
    name: "Quantity",
    type: PropertyType.NUMBER,
    position: 6,
    config: { defaultValue: 0, format: "float" },
    hint: "Об'єм позиції. Необхідний для розрахунку грошового ризику та прибутку.",
    group: "Execution",
  },
  {
    name: "Entry Date",
    type: PropertyType.DATE,
    position: 7,
    config: DATE_CONFIG,
    hint: "Час входу. Допомагає аналізувати вплив таймінгу на результат.",
    group: "Execution",
  },
  {
    name: "Exit Date",
    type: PropertyType.DATE,
    position: 8,
    config: DATE_CONFIG,
    hint: "Час виходу. Використовується для розрахунку тривалості утримання позиції.",
    group: "Execution",
  },
  {
    name: "Initial SL",
    type: PropertyType.NUMBER,
    position: 9,
    config: { defaultValue: 0, format: "float" },
    hint: "Ціна, за якої ідея вважається невалідною. Ключове поле для розрахунку ризику.",
    group: "Risk Management",
  },
  {
    name: "Initial TP",
    type: PropertyType.NUMBER,
    position: 10,
    config: { defaultValue: 0, format: "float" },
    hint: "Цільова ціна виходу. Потрібна для оцінки математичного очікування (Planned R).",
    group: "Risk Management",
  },
  {
    name: "Risk Amount ($)",
    type: PropertyType.FORMULA,
    position: 11,
    config: FORMULA_TEXT,
    hint: "Сума, яку ви втратите при досягненні Stop Loss.",
    group: "Risk Management",
  },
  {
    name: "Risk %",
    type: PropertyType.FORMULA,
    position: 12,
    config: FORMULA_TEXT,
    hint: "Відсоток від капіталу під загрозою. Базовий показник ризик-менеджменту.",
    group: "Risk Management",
  },
  {
    name: "Planned R",
    type: PropertyType.FORMULA,
    position: 13,
    config: FORMULA_TEXT,
    hint: "Потенційна винагорода відносно ризику.",
    group: "Risk Management",
  },
  {
    name: "Actual R",
    type: PropertyType.FORMULA,
    position: 14,
    config: FORMULA_TEXT,
    hint: "Фактичне R-кратне в одиницях ризику. Головний показник стабільності.",
    group: "Risk Management",
  },
  {
    name: "Gross P&L",
    type: PropertyType.FORMULA,
    position: 15,
    config: FORMULA_TEXT,
    hint: "Результат угоди без урахування витрат.",
    group: "Risk Management",
  },
  {
    name: "Fees",
    type: PropertyType.NUMBER,
    position: 16,
    config: { defaultValue: 0, format: "float" },
    hint: "Сумарні витрати на комісії та свопи.",
    group: "Risk Management",
  },
  {
    name: "Net P&L",
    type: PropertyType.FORMULA,
    position: 17,
    config: FORMULA_TEXT,
    hint: "Реальний прибуток, який залишився на балансі після всіх витрат.",
    group: "Risk Management",
  },
  {
    name: "Narrative Timeframe",
    type: PropertyType.SELECT,
    position: 18,
    config: { isMultiSelect: false, categories: [{ label: "Timeframe", options: TIMEFRAME_OPTIONS }] },
    hint: "Основний таймфрейм, на якому ви визначили напрямок руху.",
    group: "Context & Execution",
  },
  {
    name: "Execution Timeframe",
    type: PropertyType.SELECT,
    position: 19,
    config: { isMultiSelect: false, categories: [{ label: "Timeframe", options: TIMEFRAME_OPTIONS }] },
    hint: "Таймфрейм, де ви шукали конкретну точку входу.",
    group: "Context & Execution",
  },
  {
    name: "Point A (Origin)",
    type: PropertyType.TEXT,
    position: 20,
    hint: "Логічна точка старту цінового імпульсу (напр. свіп або POI).",
    group: "Context & Execution",
  },
  {
    name: "Point B (Target)",
    type: PropertyType.TEXT,
    position: 21,
    hint: "Куди саме 'тягне' ціну ринковий магніт (напр. ціль або DOL).",
    group: "Context & Execution",
  },
  {
    name: "Entry Model",
    type: PropertyType.SELECT,
    position: 22,
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Entry Models",
          options: [
            { value: "Breakout", color: colors.blue },
            { value: "Retest", color: colors.purple },
            { value: "Reversal", color: colors.red },
            { value: "Sweep+MSS", color: colors.amber },
            { value: "Silver Bullet", color: colors.gold },
            { value: "Turtle Soup", color: colors.pink },
          ],
        },
      ],
    },
    hint: "Конкретний механічний сетап, що став тригером для входу.",
    group: "Context & Execution",
  },
  {
    name: "Session / Time",
    type: PropertyType.SELECT,
    position: 23,
    config: { isMultiSelect: false, categories: [{ label: "Session", options: SESSION_OPTIONS }] },
    hint: "Торговий період. Допомагає знайти залежність від часу доби.",
    group: "Context & Execution",
  },
  {
    name: "Confidence",
    type: PropertyType.RATING,
    position: 24,
    hint: "Ваша внутрішня впевненість у сетапі в момент натискання кнопки.",
    group: "Psychology & Discipline",
  },
  {
    name: "Plan Adherence",
    type: PropertyType.SELECT,
    position: 25,
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Plan Adherence",
          options: [
            { value: "Followed", color: colors.green },
            { value: "Partial", color: colors.amber },
            { value: "Broken", color: colors.red },
          ],
        },
      ],
    },
    hint: "Наскільки точно ви виконали свій торговий план.",
    group: "Psychology & Discipline",
  },
  {
    name: "Emotion",
    type: PropertyType.SELECT,
    position: 26,
    config: {
      isMultiSelect: true,
      categories: [
        {
          label: "Emotions",
          options: [
            { value: "Calm", color: colors.green },
            { value: "Anxious", color: colors.amber },
            { value: "FOMO", color: colors.pink },
            { value: "Greed", color: colors.gold },
            { value: "Fear", color: colors.red },
            { value: "Revenge", color: colors.brown },
            { value: "Bored", color: colors.gray },
            { value: "Overconfident", color: colors.purple },
          ],
        },
      ],
    },
    hint: "Емоційний фон під час торгівлі. Виявляє психологічні 'витоки'.",
    group: "Psychology & Discipline",
  },
  {
    name: "MFE (Max Fav)",
    type: PropertyType.NUMBER,
    position: 27,
    config: { defaultValue: 0, format: "float" },
    hint: "Максимальна ціна, до якої доходив ринок, поки ви були в угоді.",
    group: "Advanced",
  },
  {
    name: "MAE (Max Adv)",
    type: PropertyType.NUMBER,
    position: 28,
    config: { defaultValue: 0, format: "float" },
    hint: "Найгірша ціна під час угоди. Виявляє занадто 'тугі' стоп-лосси.",
    group: "Advanced",
  },
  {
    name: "Exit Efficiency",
    type: PropertyType.FORMULA,
    position: 29,
    config: FORMULA_TEXT,
    hint: "Наскільки вчасно ви вийшли. 100% — вихід на самому піку (MFE).",
    group: "Advanced",
  },
  {
    name: "Hold Time",
    type: PropertyType.FORMULA,
    position: 30,
    config: FORMULA_TEXT,
    hint: "Тривалість угоди. Допомагає оптимізувати час очікування.",
    group: "Advanced",
  },
  {
    name: "Trading System",
    type: PropertyType.RELATION,
    position: 31,
    config: { sourceDatabaseType: "trading-system", multiple: false },
    hint: "Прив'язка до конкретної стратегії для аналізу її загальної ефективності.",
    group: "Relations",
  },
  {
    name: "Account",
    type: PropertyType.RELATION,
    position: 32,
    config: { sourceDatabaseType: "accounts", multiple: false },
    hint: "Вказує, на якому рахунку відбувалася торгівля.",
    group: "Relations",
  },
  {
    name: "Daily Routine",
    type: PropertyType.RELATION,
    position: 33,
    config: { sourceDatabaseType: "daily-routine", multiple: false },
    hint: "Пов'язує угоду з контекстом дня (аналізом до сесії).",
    group: "Relations",
  },
  {
    name: "Notes",
    type: PropertyType.RELATION,
    position: 34,
    config: { sourceDatabaseType: "notes", multiple: true },
    hint: "Специфічні уроки або спостереження, отримані з цієї угоди.",
    group: "Relations",
  },
  {
    name: "Mistakes",
    type: PropertyType.RELATION,
    position: 35,
    config: { sourceDatabaseType: "mistakes", multiple: true },
    hint: "Помилки, які були допущені. Необхідно для розрахунку їхньої вартості.",
    group: "Relations",
  },
  {
    name: "Outcome",
    type: PropertyType.SELECT,
    position: 36,
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Outcome",
          options: [
            { value: "Win", color: colors.green },
            { value: "Loss", color: colors.red },
            { value: "Breakeven", color: colors.gray },
          ],
        },
      ],
    },
    hint: "Фінальний результат угоди. Використовується для розрахунку Win Rate.",
    group: "Execution",
  },
];
