import { PropertyType } from "@fixspace/domain";
import { colors, DATE_CONFIG, PAIR_CATEGORIES, SESSION_OPTIONS, TIMEFRAME_OPTIONS } from "../constants";
import type { InitPropertyDef } from "../types";

export const tradingSystemProperties: InitPropertyDef[] = [
  {
    name: "Name",
    type: PropertyType.TEXT,
    position: 0,
    hint: "Назва торговельної системи або стратегії",
  },
  {
    name: "Date",
    type: PropertyType.DATE,
    position: 1,
    icon: "icon:Calendar",
    config: DATE_CONFIG,
    hint: "Дата створення системи",
  },
  {
    name: "Status",
    type: PropertyType.SELECT,
    position: 2,
    icon: "icon:List",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Status",
          options: [
            { value: "Active", color: colors.blue },
            { value: "Testing", color: colors.amber },
            { value: "Paused", color: colors.gray },
            { value: "Retired", color: colors.red },
          ],
        },
      ],
    },
    hint: "Поточний статус системи в lifecycle",
  },
  {
    name: "Category",
    type: PropertyType.SELECT,
    position: 3,
    icon: "icon:Tag",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Category",
          options: [
            { value: "Trend Following", color: colors.green },
            { value: "Mean Reversion", color: colors.blue },
            { value: "Breakout", color: colors.purple },
            { value: "SMC/ICT", color: colors.amber },
            { value: "Scalping", color: colors.pink },
            { value: "Swing", color: colors.gold },
            { value: "Position Trading", color: colors.brown },
          ],
        },
      ],
    },
    hint: "Стиль та підхід торговельної системи",
  },
  {
    name: "Market Type",
    type: PropertyType.SELECT,
    position: 4,
    icon: "icon:ChartLine",
    config: {
      isMultiSelect: true,
      categories: [
        {
          label: "Market Type",
          options: [
            { value: "Trending", color: colors.green },
            { value: "Ranging", color: colors.blue },
            { value: "High Volatility", color: colors.red },
            { value: "Low Volatility", color: colors.gray },
          ],
        },
      ],
    },
    hint: "Умови ринку, в яких система найефективніша",
  },
  {
    name: "Pairs",
    type: PropertyType.SELECT,
    position: 5,
    icon: "icon:TrendingUp",
    config: { isMultiSelect: true, categories: PAIR_CATEGORIES },
    hint: "Інструменти, для яких розроблена система",
  },
  {
    name: "Timeframes",
    type: PropertyType.SELECT,
    position: 6,
    icon: "icon:Clock",
    config: { isMultiSelect: true, categories: [{ label: "Timeframe", options: TIMEFRAME_OPTIONS }] },
    hint: "Основні таймфрейми системи",
  },
  {
    name: "Sessions",
    type: PropertyType.SELECT,
    position: 7,
    icon: "icon:Sun",
    config: { isMultiSelect: true, categories: [{ label: "Session", options: SESSION_OPTIONS }] },
    hint: "Торгові сесії, для яких призначена система",
  },
  {
    name: "Risk Per Trade %",
    type: PropertyType.NUMBER,
    position: 8,
    icon: "icon:Shield",
    config: { defaultValue: 1, format: "float" },
    hint: "Максимальний % капіталу під ризиком на одну угоду",
  },
  {
    name: "Max Daily Loss %",
    type: PropertyType.NUMBER,
    position: 9,
    icon: "icon:ArrowDown",
    config: { defaultValue: 3, format: "float" },
    hint: "Денний стоп — при досягненні цього рівня торгівля зупиняється",
  },
  {
    name: "Max Simultaneous Trades",
    type: PropertyType.NUMBER,
    position: 10,
    icon: "icon:Layers",
    config: { defaultValue: 1, format: "integer" },
    hint: "Максимальна кількість одночасно відкритих позицій",
  },
  {
    name: "Min Sample Size",
    type: PropertyType.NUMBER,
    position: 11,
    icon: "icon:Sigma",
    config: { defaultValue: 50, format: "integer" },
    hint: "Мінімальна кількість угод для валідної статистичної оцінки edge",
  },
  {
    name: "Trades",
    type: PropertyType.RELATION,
    position: 12,
    config: { sourceDatabaseType: "trading-journal", multiple: true, reversePropertyName: "Trading System" },
    hint: "Всі угоди, виконані за цією системою",
  },
  {
    name: "Total Trades",
    type: PropertyType.FORMULA,
    position: 13,
    config: {
      type: "CUSTOM",
      expression: "COUNT({{Trades}})",
      resultType: "NUMBER",
    },
    hint: "Загальна кількість угод по системі",
  },
  {
    name: "Total R",
    type: PropertyType.FORMULA,
    position: 14,
    config: {
      type: "CUSTOM",
      expression: "SUM(MAP({{Trades}}, 'Actual R'))",
      resultType: "NUMBER",
    },
    hint: "Сумарне R-кратне — загальний результат системи в одиницях ризику",
  },
  {
    name: "Avg R",
    type: PropertyType.FORMULA,
    position: 15,
    config: {
      type: "CUSTOM",
      expression: "IF(COUNT({{Trades}}) == 0, 0, AVG(MAP({{Trades}}, 'Actual R')))",
      resultType: "NUMBER",
    },
    hint: "Середнє R-кратне на угоду — показник якості виконання системи",
  },
  {
    name: "Win Rate",
    type: PropertyType.FORMULA,
    position: 16,
    config: {
      type: "CUSTOM",
      expression: "IF(COUNT({{Trades}}) == 0, 0, SUM(MAP({{Trades}}, 'Is Win')) / COUNT({{Trades}}) * 100)",
      resultType: "NUMBER",
    },
    hint: "Відсоток прибуткових угод по системі (залежить від поля 'Is Win' у Trading Journal)",
  },
  {
    name: "Profit Factor",
    type: PropertyType.NUMBER,
    position: 17,
    config: { defaultValue: 0, format: "float" },
    hint: "Сума виграшів / Сума програшів. Значення > 1.5 — хороша система",
  },
  {
    name: "Expectancy",
    type: PropertyType.NUMBER,
    position: 18,
    config: { defaultValue: 0, format: "float" },
    hint: "Математичне очікування в R: (Win% × Avg Win R) – (Loss% × Avg Loss R). Якщо > 0 — система має статистичний edge",
  },
  {
    name: "Max Consecutive Losses",
    type: PropertyType.NUMBER,
    position: 19,
    config: { defaultValue: 0, format: "integer" },
    hint: "Максимальна серія збиткових угод підряд — критично для психологічної витривалості та розміру позиції",
  },
  {
    name: "Confidence",
    type: PropertyType.RATING,
    position: 20,
    icon: "icon:TrendingUp",
    config: { maxStars: 5, allowHalf: true },
    hint: "Рівень впевненості в системі на основі статистики та досвіду",
  },
  {
    name: "Last Updated",
    type: PropertyType.DATE,
    position: 21,
    icon: "icon:CalendarClock",
    config: DATE_CONFIG,
    hint: "Дата останнього оновлення статистики системи",
  },
];
