import { PropertyType } from "@fixspace/domain";
import { colors, DATE_CONFIG, DIRECTION_OPTIONS, PAIR_CATEGORIES, SESSION_OPTIONS, TIMEFRAME_OPTIONS } from "../constants";
import type { InitPropertyDef } from "../types";

export const tradingJournalProperties: InitPropertyDef[] = [
  {
    name: "Name",
    type: PropertyType.TEXT,
    position: 0,
    hint: "Короткий ідентифікатор угоди для швидкого пошуку в списку.",
  },
  {
    name: "Status",
    type: PropertyType.SELECT,
    position: 1,
    icon: "icon:List",
    integrationKey: "status",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Status",
          options: [
            { value: "Active", color: colors.blue },
            { value: "Closed", color: colors.gray },
          ],
        },
      ],
    },
    hint: "Відображає життєвий цикл угоди: від ідеї до повного закриття.",
  },
  {
    name: "Pair",
    type: PropertyType.SELECT,
    position: 2,
    icon: "icon:TrendingUp",
    integrationKey: "pair",
    config: { isMultiSelect: false, categories: PAIR_CATEGORIES },
    hint: "Конкретний актив. Дозволяє виявити, на яких інструментах ваша стратегія працює найкраще.",
  },
  {
    name: "Direction",
    type: PropertyType.SELECT,
    position: 3,
    icon: "icon:ArrowUpDown",
    integrationKey: "direction",
    config: { isMultiSelect: false, categories: [{ label: "Direction", options: DIRECTION_OPTIONS }] },
    hint: "Напрямок позиції. Важливо для аналізу перекосів.",
  },
  {
    name: "Entry Price",
    type: PropertyType.NUMBER,
    position: 4,
    icon: "icon:ArrowRightFromLine",
    integrationKey: "entryPrice",
    config: { defaultValue: 0, format: "float" },
    hint: "Точна ціна виконання ордера. Фундамент для розрахунку P&L та R-кратного.",
  },
  {
    name: "Exit Price",
    type: PropertyType.NUMBER,
    position: 5,
    icon: "icon:ArrowLeftFromLine",
    integrationKey: "exitPrice",
    config: { defaultValue: 0, format: "float" },
    hint: "Середня ціна виходу. Дозволяє розрахувати фактичну ефективність угоди.",
  },
  {
    name: "Quantity",
    type: PropertyType.NUMBER,
    position: 6,
    icon: "icon:ShoppingCart",
    integrationKey: "quantity",
    config: { defaultValue: 0, format: "float" },
    hint: "Об'єм позиції. Необхідний для розрахунку грошового ризику та прибутку.",
  },
  {
    name: "Entry Date",
    type: PropertyType.DATE,
    position: 7,
    icon: "icon:CalendarClock",
    integrationKey: "entryDate",
    config: DATE_CONFIG,
    hint: "Час входу. Допомагає аналізувати вплив таймінгу на результат.",
  },
  {
    name: "Exit Date",
    type: PropertyType.DATE,
    position: 8,
    icon: "icon:CalendarClock",
    integrationKey: "exitDate",
    config: DATE_CONFIG,
    hint: "Час виходу. Використовується для розрахунку тривалості утримання позиції.",
  },
  {
    name: "Outcome",
    type: PropertyType.SELECT,
    position: 9,
    icon: "icon:CheckCircle2",
    integrationKey: "outcome",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Outcome",
          options: [
            { value: "Win", color: colors.green },
            { value: "Loss", color: colors.red },
            { value: "Breakeven", color: colors.gray },
          ],
        },
      ],
    },
    hint: "Фінальний результат угоди. Використовується для розрахунку Win Rate.",
  },
  {
    name: "Initial SL",
    type: PropertyType.NUMBER,
    position: 10,
    icon: "icon:Shield",
    integrationKey: "stopLoss",
    config: { defaultValue: 0, format: "float" },
    hint: "Ціна, за якої ідея вважається невалідною. Ключове поле для розрахунку ризику.",
  },
  {
    name: "Initial TP",
    type: PropertyType.NUMBER,
    position: 11,
    icon: "icon:Crosshair",
    integrationKey: "takeProfit",
    config: { defaultValue: 0, format: "float" },
    hint: "Цільова ціна виходу. Потрібна для оцінки математичного очікування (Planned R).",
  },
  {
    name: "Risk Amount ($)",
    type: PropertyType.FORMULA,
    position: 12,
    config: {
      type: "CUSTOM",
      expression: "IF({{Initial SL}} == 0, 0, ABS({{Entry Price}} - {{Initial SL}}) * {{Quantity}})",
      resultType: "NUMBER",
    },
    hint: "Сума, яку ви втратите при досягненні Stop Loss.",
  },
  {
    name: "Risk %",
    type: PropertyType.FORMULA,
    position: 13,
    config: {
      type: "CUSTOM",
      expression: "({{Risk Amount ($)}} / 100000) * 100",
      resultType: "NUMBER",
    },
    hint: "Відсоток від капіталу під загрозою. Базовий показник ризик-менеджменту.",
  },
  {
    name: "Planned R",
    type: PropertyType.FORMULA,
    position: 14,
    config: {
      type: "CUSTOM",
      expression:
        "IF({{Direction}} == 'Long', IF({{Entry Price}} - {{Initial SL}} == 0, 0, ({{Initial TP}} - {{Entry Price}}) / ({{Entry Price}} - {{Initial SL}})), IF({{Initial SL}} - {{Entry Price}} == 0, 0, ({{Entry Price}} - {{Initial TP}}) / ({{Initial SL}} - {{Entry Price}})))",
      resultType: "NUMBER",
    },
    hint: "Потенційна винагорода відносно ризику.",
  },
  {
    name: "Actual R",
    type: PropertyType.FORMULA,
    position: 15,
    config: {
      type: "CUSTOM",
      expression:
        "IF({{Direction}} == 'Long', IF({{Entry Price}} - {{Initial SL}} == 0, 0, ({{Exit Price}} - {{Entry Price}}) / ({{Entry Price}} - {{Initial SL}})), IF({{Initial SL}} - {{Entry Price}} == 0, 0, ({{Entry Price}} - {{Exit Price}}) / ({{Initial SL}} - {{Entry Price}})))",
      resultType: "NUMBER",
    },
    hint: "Фактичне R-кратне в одиницях ризику. Головний показник стабільності.",
  },
  {
    name: "Gross P&L",
    type: PropertyType.FORMULA,
    position: 16,
    config: {
      type: "CUSTOM",
      expression:
        "IF({{Direction}} == 'Long', ({{Exit Price}} - {{Entry Price}}) * {{Quantity}}, ({{Entry Price}} - {{Exit Price}}) * {{Quantity}})",
      resultType: "NUMBER",
    },
    hint: "Результат угоди без урахування витрат.",
  },
  {
    name: "Fees",
    type: PropertyType.NUMBER,
    position: 17,
    icon: "icon:Receipt",
    integrationKey: "fees",
    config: { defaultValue: 0, format: "float" },
    hint: "Сумарні витрати на комісії та свопи.",
  },
  {
    name: "Net P&L",
    type: PropertyType.FORMULA,
    position: 18,
    config: {
      type: "CUSTOM",
      expression: "{{Gross P&L}} - {{Fees}}",
      resultType: "NUMBER",
    },
    hint: "Реальний прибуток, який залишився на балансі після всіх витрат.",
  },
  {
    name: "Narrative Timeframe",
    type: PropertyType.SELECT,
    position: 19,
    icon: "icon:Clock",
    config: { isMultiSelect: false, categories: [{ label: "Timeframe", options: TIMEFRAME_OPTIONS }] },
    hint: "Основний таймфрейм, на якому ви визначили напрямок руху.",
  },
  {
    name: "Execution Timeframe",
    type: PropertyType.SELECT,
    position: 20,
    icon: "icon:Timer",
    config: { isMultiSelect: false, categories: [{ label: "Timeframe", options: TIMEFRAME_OPTIONS }] },
    hint: "Таймфрейм, де ви шукали конкретну точку входу.",
  },
  {
    name: "Point A (Origin)",
    type: PropertyType.TEXT,
    position: 21,
    icon: "icon:MapPin",
    hint: "Логічна точка старту цінового імпульсу (напр. свіп або POI).",
  },
  {
    name: "Point B (Target)",
    type: PropertyType.TEXT,
    position: 22,
    icon: "icon:MapPin",
    hint: "Куди саме 'тягне' ціну ринковий магніт (напр. ціль або DOL).",
  },
  {
    name: "Entry Model",
    type: PropertyType.SELECT,
    position: 23,
    icon: "icon:Crosshair",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Entry Models",
          options: [
            { value: "Breakout", color: colors.blue },
            { value: "Retest", color: colors.purple },
            { value: "Reversal", color: colors.red },
            { value: "Sweep+MSS", color: colors.amber },
            { value: "Silver Bullet", color: colors.gold },
            { value: "Turtle Soup", color: colors.pink },
          ],
        },
      ],
    },
    hint: "Конкретний механічний сетап, що став тригером для входу.",
  },
  {
    name: "Session / Time",
    type: PropertyType.SELECT,
    position: 24,
    icon: "icon:Sun",
    config: { isMultiSelect: false, categories: [{ label: "Session", options: SESSION_OPTIONS }] },
    hint: "Торговий період. Допомагає знайти залежність від часу доби.",
  },
  {
    name: "Confidence",
    type: PropertyType.RATING,
    position: 25,
    icon: "icon:TrendingUp",
    config: { maxStars: 5, allowHalf: true, icon: "icon:Flame" },
    hint: "Ваша внутрішня впевненість у сетапі в момент натискання кнопки.",
  },
  {
    name: "Setup Quality",
    type: PropertyType.RATING,
    position: 26,
    icon: "icon:Star",
    config: { maxStars: 5, allowHalf: true, icon: "icon:Sparkles" },
    hint: "Об'єктивна якість сетапу по чеклисту — наскільки він чіткий і типовий (незалежно від впевненості).",
  },
  {
    name: "Plan Adherence",
    type: PropertyType.SELECT,
    position: 27,
    icon: "icon:ClipboardCheck",
    config: {
      isMultiSelect: false,
      categories: [
        {
          label: "Plan Adherence",
          options: [
            { value: "Followed", color: colors.green },
            { value: "Partial", color: colors.amber },
            { value: "Broken", color: colors.red },
          ],
        },
      ],
    },
    hint: "Наскільки точно ви виконали свій торговий план.",
  },
  {
    name: "Emotion",
    type: PropertyType.SELECT,
    position: 28,
    icon: "icon:Heart",
    config: {
      isMultiSelect: true,
      categories: [
        {
          label: "Emotions",
          options: [
            { value: "Calm", color: colors.green },
            { value: "Anxious", color: colors.amber },
            { value: "FOMO", color: colors.pink },
            { value: "Greed", color: colors.gold },
            { value: "Fear", color: colors.red },
            { value: "Revenge", color: colors.brown },
            { value: "Bored", color: colors.gray },
            { value: "Overconfident", color: colors.purple },
          ],
        },
      ],
    },
    hint: "Емоційний фон під час торгівлі. Виявляє психологічні 'витоки'.",
  },
  {
    name: "MFE (Max Fav)",
    type: PropertyType.NUMBER,
    position: 29,
    icon: "icon:ChartCandlestick",
    config: { defaultValue: 0, format: "float" },
    hint: "Максимальна ціна, до якої доходив ринок, поки ви були в угоді.",
  },
  {
    name: "MAE (Max Adv)",
    type: PropertyType.NUMBER,
    position: 30,
    icon: "icon:ChartCandlestick",
    config: { defaultValue: 0, format: "float" },
    hint: "Найгірша ціна під час угоди. Виявляє занадто 'тугі' стоп-лосси.",
  },
  {
    name: "Exit Efficiency",
    type: PropertyType.FORMULA,
    position: 31,
    config: {
      type: "CUSTOM",
      expression:
        "IF({{Direction}} == 'Long', IF({{MFE (Max Fav)}} - {{Entry Price}} == 0, 0, ({{Exit Price}} - {{Entry Price}}) / ({{MFE (Max Fav)}} - {{Entry Price}}) * 100), IF({{Entry Price}} - {{MFE (Max Fav)}} == 0, 0, ({{Entry Price}} - {{Exit Price}}) / ({{Entry Price}} - {{MFE (Max Fav)}}) * 100))",
      resultType: "PROGRESS",
    },
    hint: "Наскільки вчасно ви вийшли. 100% — вихід на самому піку (MFE).",
  },
  {
    name: "Hold Time",
    type: PropertyType.FORMULA,
    position: 32,
    config: {
      type: "CUSTOM",
      expression: "IF(IS_EMPTY({{Exit Date}}), 0, DATE_DIFF({{Entry Date}}, {{Exit Date}}, 'hours'))",
      resultType: "DURATION",
    },
    hint: "Тривалість угоди. Допомагає оновлювати час очікування.",
  },
  {
    name: "Trading System",
    type: PropertyType.RELATION,
    position: 33,
    config: { sourceDatabaseType: "trading-system", multiple: false, reversePropertyName: "Trades" },
    hint: "Прив'язка до конкретної стратегії для аналізу її загальної ефективності.",
  },
  {
    name: "Account",
    type: PropertyType.RELATION,
    position: 34,
    config: { sourceDatabaseType: "accounts", multiple: false, reversePropertyName: "Trades" },
    hint: "Вказує, на якому рахунку відбувалася торгівля.",
  },
  {
    name: "Daily Routine",
    type: PropertyType.RELATION,
    position: 35,
    config: { sourceDatabaseType: "daily-routine", multiple: false, reversePropertyName: "Trades" },
    hint: "Пов'язує угоду з контекстом дня (аналізом до сесії).",
  },
  {
    name: "Notes",
    type: PropertyType.RELATION,
    position: 36,
    config: { sourceDatabaseType: "notes", multiple: true, reversePropertyName: "Trading Journal" },
    hint: "Специфічні уроки або спостереження, отримані з цієї угоди.",
  },
  {
    name: "Mistakes",
    type: PropertyType.RELATION,
    position: 37,
    config: { sourceDatabaseType: "mistakes", multiple: true, reversePropertyName: "Trading Journal" },
    hint: "Помилки, які були допущені. Необхідно для розрахунку їхньої вартості.",
  },
  {
    name: "Is Win",
    type: PropertyType.FORMULA,
    position: 38,
    config: {
      type: "CUSTOM",
      expression: "IF({{Outcome}} == 'Win', 1, 0)",
      resultType: "NUMBER",
    },
    hint: "Допоміжне поле для агрегації Win Rate в Trading System (1 = Win, 0 = інше)",
  },
];
