import type { SeedRecord } from "./types";

export const accountsSeeds: SeedRecord[] = [
  {
    name: "FTMO 50k Challenge",
    values: {
      "Account Type": "Prop Firm",
      Status: "Active",
      "Account ID": "FTMO-50K-99281",
      Currency: "USD",
      "Starting Balance": 50000,
      "Start Date": "2025-01-01",
      Provider: "FTMO",
      Phase: "Challenge",
      "Profit Target": 10,
      "Max Overall Drawdown": 10,
      "Daily Loss Limit": 5,
      "Drawdown Type": "Static",
      "Min Trading Days": 4,
      "Profit Split": 80,
      "Challenge Fee": 345,
      "News Trading": "Restricted",
      "Weekend Holding": "Forbidden",
      "Max Position Size": 5.0,
      "Max Open Trades": 3,
      "Hard Stop Loss": true,
    },
  },
  {
    name: "Live Account — IC Markets",
    values: {
      "Account Type": "Live",
      Status: "Active",
      "Account ID": "ICM-LIVE-77625",
      Currency: "USD",
      "Starting Balance": 10000,
      "Start Date": "2025-03-01",
      Broker: "IC Markets",
      Platform: "MT5",
      Leverage: "1:30",
      "Daily Loss Limit": 200,
      "Max Position Size": 2.0,
      "Max Open Trades": 3,
      "News Trading": "Restricted",
      "Weekend Holding": "Allowed",
      "Hard Stop Loss": true,
    },
  },
  {
    name: "Demo — Strategy Test",
    values: {
      "Account Type": "Demo",
      Status: "Active",
      "Account ID": "ICM-DEMO-10023",
      Currency: "USD",
      "Starting Balance": 100000,
      "Start Date": "2025-06-01",
      Broker: "IC Markets",
      Platform: "MT5",
      Leverage: "1:100",
      "Max Overall Drawdown": 20,
      "Daily Loss Limit": 2000,
      "Max Position Size": 10.0,
      "Max Open Trades": 5,
      "News Trading": "Allowed",
      "Weekend Holding": "Allowed",
      "Hard Stop Loss": false,
    },
  },
];
