import type { SeedRecord } from "./types";

export const tradingJournalSeeds: SeedRecord[] = [
  {
    name: "EURUSD Intraday Long",
    relations: {
      Account: { type: "accounts", name: "FTMO 50k Challenge" },
      "Daily Routine": { type: "daily-routine", name: "Daily Log - 2025-01-15" },
      "Trading System": { type: "trading-system", name: "Intraday Strategy" },
      Notes: { type: "notes", name: "FVG Entry Rules" },
    },
    values: {
      Status: "Closed",
      Pair: "EURUSD",
      Direction: "Long",
      Outcome: "Win",
      "Entry Price": 1.085,
      "Exit Price": 1.089,
      Quantity: 5.0,
      "Entry Date": "2025-01-15",
      "Exit Date": "2025-01-15",
      "Initial SL": 1.083,
      "Initial TP": 1.09,
      "Narrative Timeframe": "4H",
      "Execution Timeframe": "15m",
      "Point A (Origin)": "Asian Low Sweep",
      "Point B (Target)": "Daily FVG",
      "Entry Model": "Sweep+MSS",
      "Session / Time": "London",
      Confidence: 4,
      "Setup Quality": 4,
      "Plan Adherence": "Followed",
      Emotion: ["Calm"],
      "MFE (Max Fav)": 1.0895,
      "MAE (Max Adv)": 1.0845,
      Fees: 25.0,
    },
  },
  {
    name: "GBPUSD Swing Short",
    relations: {
      Account: { type: "accounts", name: "Live Account — IC Markets" },
      "Daily Routine": { type: "daily-routine", name: "Daily Log - 2025-01-16" },
      "Trading System": { type: "trading-system", name: "Swing Strategy" },
      Notes: { type: "notes", name: "Order Block Identification" },
      Mistakes: { type: "mistakes", name: "Revenge Trading" },
    },
    values: {
      Status: "Closed",
      Pair: "GBPUSD",
      Direction: "Short",
      Outcome: "Win",
      "Entry Price": 1.272,
      "Exit Price": 1.262,
      Quantity: 1.0,
      "Entry Date": "2025-01-16",
      "Exit Date": "2025-01-19",
      "Initial SL": 1.277,
      "Initial TP": 1.255,
      "Narrative Timeframe": "Daily",
      "Execution Timeframe": "1H",
      "Point A (Origin)": "Weekly Order Block",
      "Point B (Target)": "Previous Month Low",
      "Entry Model": "Retest",
      "Session / Time": "New York",
      Confidence: 5,
      "Setup Quality": 3,
      "Plan Adherence": "Broken",
      Emotion: ["FOMO", "Revenge"],
      "MFE (Max Fav)": 1.261,
      "MAE (Max Adv)": 1.274,
      Fees: 10.0,
    },
  },
  {
    name: "XAUUSD Breakout Short",
    relations: {
      Account: { type: "accounts", name: "FTMO 50k Challenge" },
      "Daily Routine": { type: "daily-routine", name: "Daily Log - 2025-01-17" },
      "Trading System": { type: "trading-system", name: "Swing Strategy" },
      Notes: { type: "notes", name: "Order Block Identification" },
    },
    values: {
      Status: "Closed",
      Pair: "XAUUSD",
      Direction: "Short",
      Outcome: "Win",
      "Entry Price": 2045.0,
      "Exit Price": 2035.0,
      Quantity: 10.0,
      "Entry Date": "2025-01-17",
      "Exit Date": "2025-01-17",
      "Initial SL": 2050.0,
      "Initial TP": 2030.0,
      "Narrative Timeframe": "Daily",
      "Execution Timeframe": "15m",
      "Point A (Origin)": "Previous Day High Sweep",
      "Point B (Target)": "Weekly FVG",
      "Entry Model": "Turtle Soup",
      "Session / Time": "New York",
      Confidence: 5,
      "Setup Quality": 5,
      "Plan Adherence": "Followed",
      Emotion: ["Calm"],
      "MFE (Max Fav)": 2032.0,
      "MAE (Max Adv)": 2046.5,
      Fees: 45.0,
    },
  },
  {
    name: "EURUSD Fomo Loss",
    relations: {
      Account: { type: "accounts", name: "Live Account — IC Markets" },
      "Daily Routine": { type: "daily-routine", name: "Daily Log - 2025-01-16" },
      "Trading System": { type: "trading-system", name: "Intraday Strategy" },
      Mistakes: { type: "mistakes", name: "Revenge Trading" },
    },
    values: {
      Status: "Closed",
      Pair: "EURUSD",
      Direction: "Long",
      Outcome: "Loss",
      "Entry Price": 1.092,
      "Exit Price": 1.087,
      Quantity: 8.0,
      "Entry Date": "2025-01-16",
      "Exit Date": "2025-01-16",
      "Initial SL": 1.087,
      "Initial TP": 1.1,
      "Narrative Timeframe": "1H",
      "Execution Timeframe": "5m",
      "Point A (Origin)": "Impulse top",
      "Point B (Target)": "Liquidity Pool",
      "Entry Model": "Breakout",
      "Session / Time": "New York",
      Confidence: 2,
      "Setup Quality": 2,
      "Plan Adherence": "Broken",
      Emotion: ["FOMO", "Anxious"],
      "MFE (Max Fav)": 1.0935,
      "MAE (Max Adv)": 1.087,
      Fees: 30.0,
    },
  },
];
