import type { SeedRecord } from "./types";

export const tradingJournalSeeds: SeedRecord[] = [
  {
    name: "EURUSD Intraday Long",
    relations: {
      Account: { type: "accounts", name: "Prop Account 50k" },
      "Daily Routine": { type: "daily-routine", name: "Daily Log - 2025-01-15" },
      "Trading System": { type: "trading-system", name: "Intraday Strategy" },
      Notes: { type: "notes", name: "FVG Entry Rules" },
    },
    values: {
      Status: "Closed",
      Pair: "EURUSD",
      Direction: "Long",
      "Entry Price": 1.085,
      "Exit Price": 1.089,
      Quantity: 5.0,
      "Entry Date": "2025-01-15",
      "Exit Date": "2025-01-15",
      "Initial SL": 1.083,
      "Initial TP": 1.09,
      "Risk Amount ($)": 100.0,
      "Risk %": "0.2%",
      "Planned R": 2.5,
      "Actual R": 2.0,
      "Gross P&L": 200.0,
      Fees: 25.0,
      "Net P&L": 175.0,
      "Narrative Timeframe": "4H",
      "Execution Timeframe": "15m",
      "Point A (Origin)": "Asian Low Sweep",
      "Point B (Target)": "Daily FVG",
      "Entry Model": "Sweep+MSS",
      "Session / Time": "London",
      Confidence: 4,
      "Plan Adherence": "Followed",
      Emotion: ["Calm"],
      "MFE (Max Fav)": 1.0895,
      "MAE (Max Adv)": 1.0845,
      "Exit Efficiency": "90%",
      "Hold Time": "2h 0m",
    },
  },
  {
    name: "GBPUSD Swing Short",
    relations: {
      Account: { type: "accounts", name: "Personal Live Account" },
      "Daily Routine": { type: "daily-routine", name: "Daily Log - 2025-01-16" },
      "Trading System": { type: "trading-system", name: "Swing Strategy" },
      Notes: { type: "notes", name: "Order Block Identification" },
      Mistakes: { type: "mistakes", name: "Revenge Trading" },
    },
    values: {
      Status: "Closed",
      Pair: "GBPUSD",
      Direction: "Short",
      "Entry Price": 1.272,
      "Exit Price": 1.262,
      Quantity: 1.0,
      "Entry Date": "2025-01-16",
      "Exit Date": "2025-01-19",
      "Initial SL": 1.277,
      "Initial TP": 1.255,
      "Risk Amount ($)": 50.0,
      "Risk %": "0.5%",
      "Planned R": 3.4,
      "Actual R": 2.0,
      "Gross P&L": 100.0,
      Fees: 10.0,
      "Net P&L": 90.0,
      "Narrative Timeframe": "Daily",
      "Execution Timeframe": "1H",
      "Point A (Origin)": "Weekly Order Block",
      "Point B (Target)": "Previous Month Low",
      "Entry Model": "Retest",
      "Session / Time": "New York",
      Confidence: 5,
      "Plan Adherence": "Broken",
      Emotion: ["FOMO", "Revenge"],
      "MFE (Max Fav)": 1.261,
      "MAE (Max Adv)": 1.274,
      "Exit Efficiency": "80%",
      "Hold Time": "2d 19h",
    },
  },
];
