name: Mirror to GitLab

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug secrets
        run: |
          echo "REPO='${GITLAB_REPO}'"
          if [ -z "${GITLAB_REPO}" ]; then echo "REPO IS EMPTY"; fi

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO}
          git push gitlab --all
          git push gitlab --tags
